### ISSUE TITLE
rticles package

### ISSUE THREAD

**Issue by Auburngrads** [AFIT-R/sure-manuscript#1]
@bgreenwell I realize that this may be a bad time to ask this question, but why aren't you using the [`rticles`](https://github.com/rstudio/rticles) package to write this paper for the R Journal?

**Comment by bgreenwell** [comment]
Because 'rticles' does not always reflect the current style of the R Journal, which just underwent some changes. But also, sometimes knitr and LaTeX is just better in my opinion! 😎 Also, I think Brad ran into a few issues using rticles for an R Journal submission.

**Comment by bradleyboehmke** [comment]
Yeah, the `rticles` package does not produce the proper documentation for an R Journal submission and the associate editor handling my submission made me well aware of the fact that my original submission with `rticles` was far from sufficient!

**Comment by Auburngrads** [comment]
With all of the packages that RStudio maintains I wondered how well they kept them up to date. Still seems like someone at RJ could just make a pull request with the changes. Did RJ give a list of issues to be fixed?
